version: "3.9"
services:
  db:
    image: postgres:17
    container_name: tpo-lab2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tpo-lab2
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: